In [ ]:
#Array
#Practice questions: Easy

In [ ]:
# 1. Write a program to find the smallest element among N inputted numbers

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])

def array(arr):
    min_val=np.min(arr)
    return min_val

result=array(arr)
print(result)


1


In [ ]:
# 2. Write a program to rearrange an array in reverse order without using a second array.

In [4]:
arr=np.array([7,3,4,6,8,2])

def array(arr):
    print(arr[::-1])

array(arr)

[2 8 6 4 3 7]


In [ ]:
# 3. Write a program to calculate standard deviation of N numbers 

In [5]:
arr=np.array([7,3,4,5,6,9,8])
def calc(arr):
    l=len(arr)
    sum=0
    n=[]
    m=0
    for x in arr:
        sum=sum+x

    mean=sum/l
    for x in arr:
        v=(x-mean)**2
        n.append(v)

    for i in n:
        m=i+m

    variance=m/l
    standard_deviation=(variance)**0.5
    return standard_deviation

     

In [6]:
calc(arr)

2.0

In [ ]:
# 4. Write a program to count odd numbers in a set of integers

In [7]:
arr=np.array([7,3,4,5,6,9,8])
def int(arr):
    count=0
    for i in arr:
        if i%2==1:
            count+=1

    return count

int(arr)

4

In [ ]:
# 5. Write a program to largest odd number in a set of integers.

In [9]:
arr=np.array([7,3,4,5,6,9,8])
def int(arr):
    new=[]
    for i in arr:
        if i%2==1:
            new.append(i)

    x=np.max(new)
    return x

int(arr)

9

In [ ]:
# 6. Write a program to count the total number of prime numbers in a set of integers

In [1]:


import numpy as np

def is_prime(n):
   
    if n < 2:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

def count_primes(arr):
   
    count = 0
    primes = []  
    for num in arr:
        if is_prime(num):
            primes.append(num)
            count += 1
    print("Prime numbers:", primes) 
    return count


arr = np.array([7, 3, 4, 5, 6, 9, 8])
print("Total prime numbers:", count_primes(arr))


Prime numbers: [7, 3, 5]
Total prime numbers: 3


In [ ]:
# 7. Write a program to find the second highest element among N inputted numbers. 

In [3]:
arr=np.array([7,3,4,5,6,9,8])
def calc(arr):
    x=np.sort(arr)
    y=x[-2]
    return y

calc(arr)

8

In [ ]:
# 8. Write a program to find the largest difference in a set of numbers

In [9]:
arr=np.array([7,3,4,5,6,9,8])
def calc(arr):
    x=[]
    for n in arr:
        y=n-arr[0]
        x.append(y)
    
    w=np.max(x)
    return w

calc(arr)
        

2

In [ ]:
# 9. Write a program to find the binary equivalent of a decimal numbers

In [11]:
def decimal_to_binary(n):
    
    binary = ""
    
    
    if n == 0:
        return "0"
    
    
    while n > 0:
        binary = str(n % 2) + binary  
        n = n // 2  
    
    return binary


decimal_number = int(input("Enter a decimal number: "))
binary_representation = decimal_to_binary(decimal_number)
print(f"The binary equivalent of {decimal_number} is {binary_representation}")


Enter a decimal number:  13


The binary equivalent of 13 is 1101


In [ ]:
# 10. Write a program to delete an element from the k-th position of an array.

In [12]:
arr=np.array([7,3,4,5,6,9,8])
def calc(arr,k):
    return np.delete(arr,k)

calc(arr,2)
    

array([7, 3, 5, 6, 9, 8])

In [ ]:
# 11. Write a program to insert an element at its proper position in a previously sorted array.

In [13]:
arr=np.array([7,3,4,5,6,9,8])
def calc(arr,k,element):
    return np.insert(arr,k,element)

calc(arr,2,77)

array([ 7,  3, 77,  4,  5,  6,  9,  8])

In [ ]:
# 12. Write a program to find the union of two sets of numbers

In [19]:
import numpy as np

def calc(arr, narr):
    a = set(arr)  
    b = set(narr)  
    return a | b  


arr = np.array([7, 3, 4, 5, 6, 9, 8])
narr = np.array([1, 2, 3, 4, 5, 6, 7])

union_result = calc(arr, narr)
print(f"The union of the two arrays is: {union_result}")


The union of the two arrays is: {1, 2, 3, 4, 5, 6, 7, 8, 9}


In [ ]:
# Practice questions: Intermediate

In [ ]:
#  1. Move Zeroes to the End
     #  • Problem: Write a function that moves all zeroes in an array to the end
     #  while maintaining the relative order of the non-zero elements.
     #  • Input: arr = [0, 1, 0, 3, 12]
     #  • Output: [1, 3, 12, 0, 0]

In [24]:
def move_zeroes_to_end(arr):
    
    non_zero_index = 0  
    
    
    for i in range(len(arr)):
        if arr[i] != 0:
            arr[non_zero_index] = arr[i]
            if non_zero_index != i:
                arr[i] = 0  
            non_zero_index += 1

    return arr


arr = [0, 1, 0, 3, 12]
result = move_zeroes_to_end(arr)
print(f"Array after moving zeroes to the end: {result}")


Array after moving zeroes to the end: [1, 3, 12, 0, 0]


In [ ]:
# 2. Array rotation
  # • Problem : write a python function to rotate an array to the right kth
  #position.
  #• Input: arr = [1,2,3,4,5]
  #• Output: [4,5,1,2,3]

In [26]:
def new(k):
    arr=[10,20,30,40]
    n=len(arr)
    if k>n:
        k=k-n
    elif k==0:
        print('no rotation')
    else:
        return arr[k:]+arr[:k] 

new(3)

[40, 10, 20, 30]

In [ ]:
# 3. Product of All Elements Except Itself
    #• Problem: Given an array of integers, return a new array such that each
    #element at index i is the product of all the numbers in the array except
    #the one at i.
    #• Input: arr = [1, 2, 3, 4]
    #• Output: [24, 12, 8, 6]

In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4])
m = [] 


for i in range(len(arr)):
    prod = 1
    for j in range(len(arr)):
        if i != j:
            prod *= arr[j]
    m.append(prod)

print(m)



[24, 12, 8, 6]


In [ ]:
# 4. Two Sum Problem
     #• Problem: Given an array of integers and a target value, return the indices
     #of the two numbers such that they add up to the target.
     #• Input: arr = [2, 7, 11, 15], target = 9
     #• Output: [0, 1] (because arr[0] + arr[1] == 9

In [31]:
def two_sum(arr, target):
   
    num_map = {}
    
    
    for i, num in enumerate(arr):
        
        complement = target - num
        
        
        if complement in num_map:
            
            return [num_map[complement], i]
        
        
        num_map[num] = i
    
    
    return None


arr = [2, 7, 11, 15]
target = 9
result = two_sum(arr, target)
print(result) 


[0, 1]


In [ ]:
# 5. Minimum Number of Jumps to Reach End
     #• Problem: Given an array of integers where each element represents the
     #  maximum jump length from that position, determine the minimum number
     #  of jumps required to reach the end of the array.
     #  • Input: arr = [6, 2, 4, 0, 5, 1, 1, 4, 2, 9]
     #  • Output: 2 (The minimum jumps to reach the end are 6 -> 5 -> 9)

In [32]:
def min_jumps(arr):
    n = len(arr)
    
    
    if n <= 1:
        return 0
    
    jumps = 0
    farthest = 0
    current_end = 0
    
    for i in range(n):
        
        farthest = max(farthest, i + arr[i])
        
        
        if i == current_end:
            jumps += 1
            current_end = farthest
            
            
            if current_end >= n - 1:
                break
    
    return jumps


arr = [6, 2, 4, 0, 5, 1, 1, 4, 2, 9]
print(min_jumps(arr)) 


2


In [ ]:
# 6. Sort Colors (Dutch National Flag Problem)
#    • Problem: Given an array containing n objects, where each object is one of
#     three colors represented by integers 0, 1, and 2, sort the array in-place
#     without using extra space.
#     • Input: arr = [2, 0, 2, 1, 1, 0]
#     • Output: [0, 0, 1, 1, 2, 2

In [33]:
def sort_colors(arr):
    low = 0
    mid = 0
    high = len(arr) - 1
    
    while mid <= high:
        if arr[mid] == 0:
            arr[low], arr[mid] = arr[mid], arr[low] 
            low += 1
            mid += 1
        elif arr[mid] == 1:
            mid += 1 
        else:  # arr[mid] == 2
            arr[mid], arr[high] = arr[high], arr[mid] 
            high -= 1
    
    return arr


arr = [2, 0, 2, 1, 1, 0]
print(sort_colors(arr))  


[0, 0, 1, 1, 2, 2]


In [ ]:
# 7. Trapping Rain Water
#    • Problem: Given an array representing the heights of bars, compute how
#    much water it can trap after raining.
#    • Input: arr = [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]
#    • Output: 6 (total water trapped)

In [34]:
def trap(arr):
    n = len(arr)
    if n <= 2:
        return 0 

    left, right = 0, n - 1
    left_max, right_max = arr[left], arr[right]
    water_trapped = 0

    while left <= right:
        if arr[left] <= arr[right]:
            if arr[left] >= left_max:
                left_max = arr[left]
            else:
                water_trapped += left_max - arr[left]
            left += 1
        else:
            if arr[right] >= right_max:
                right_max = arr[right]
            else:
                water_trapped += right_max - arr[right]
            right -= 1

    return water_trapped


arr = [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]
print(trap(arr))  


6
